### ISSUE TITLE
add CRONJOB for evaluation process to run automatically

### ISSUE THREAD

**Issue by k00ni** [k00ni/LODStats_WWW#3]

**Comment by earthquakesan** [comment]
You can start processing as in this script:
https://github.com/AKSW/lodstats.docker/blob/master/web/start_processing.sh

Basically you need to this paster command: https://github.com/AKSW/LODStats_WWW/blob/master/rdfstats/commands/process_all_datasets.py

It gets all the "active" datasets from RDFDoc model and push it to rabbitmq queue for processing (just populates the whole queue).

To start "listener", which processes the queue you need to start this paster command:
https://github.com/AKSW/LODStats_WWW/blob/master/rdfstats/commands/lodstats_listener.py

All paster commands are declared in setup.py: https://github.com/AKSW/LODStats_WWW/blob/master/setup.py

The RDFDoc ("rdfdoc" table in postgres) model contains all the datasets to be processed:
https://github.com/AKSW/LODStats_WWW/blob/master/rdfstats/model/__init__.py
