### ISSUE TITLE
re-implement gathering process

### ISSUE THREAD

**Issue by k00ni** [k00ni/LODStats_WWW#4]
Info from develop @earthquakesan:
> - gathering part has to be updated, I run it with special script previously
> - Ciro was collecting the data from CKAN portals (he got it on DBpedia servers)
what needs to be done is asking him for the list and then updating the DB with that info
> - the table with datasets is fairly simple

**Comment by earthquakesan** [comment]
The processing queue is populated from "rdfdoc" postgres table. See the RDFDoc model in this file:
https://github.com/AKSW/LODStats_WWW/blob/master/rdfstats/model/__init__.py

The important fields to populate for new datasets are:
    uri = schema.Column(types.Text())
    name = schema.Column(types.Unicode(255)) # (as in ckan)
    format = schema.Column(types.Unicode(255)) # nt, rdf, n3, nquads, turtle
    in_datahub = schema.Column(types.Boolean) # legacy, needs to be refactored out
    ckan_catalog = schema.Column(types.Text(), schema.ForeignKey('ckan_catalog.name', 
                        use_alter=True, name='rdfdoc_ckan_catalog_fkey')) # see ckan_catalog table

In case the dataset is not in CKAN instance anymore, I mark it as active=False (boolean).

**Comment by GeorgesAlkhouri** [comment]
@earthquakesan , to my understanding the rdfdoc table contains all RDF dumps which you used to create LODStats. Is this correct? 
I do not fully understand how you created the rdfdoc model. At some point you have to collect all RDF dump information and put them in the rdfdoc table, don't you? Where do you do this? Where do you get this RDF dump information?
Thanks a lot.

**Comment by k00ni** [comment]
*ping* :)

**Comment by earthquakesan** [comment]
The original idea was to populate it using script as here: https://github.com/AKSW/LODStats_WWW/blob/master/rdfstats/commands/lodstats_update.py

For the last update I used this library to collect RDF datasets from 3 CKAN repos: https://github.com/AKSW/ckan-aggregator-py

Then the results were pickled and loaded using this script:
https://github.com/AKSW/LODStats_WWW/blob/master/rdfstats/commands/synchronize_ckan.py
